CREATE TYPE "ShopPlan" AS ENUM ('START', 'BUSINESS', 'PRO');

ALTER TABLE "shops"
ADD COLUMN "owner_name" TEXT NOT NULL DEFAULT '',
ADD COLUMN "phone" TEXT NOT NULL DEFAULT '',
ADD COLUMN "plan" "ShopPlan" NOT NULL DEFAULT 'START';
